### ISSUE TITLE
ixgbevf 3.3.2 doesn't support InterruptThrottleRate=1,1,1,1,1,1,1,1

### ISSUE THREAD

**Issue by nichenke** [BashtonLtd/centos7-ami#3]
I ran into this trying to boot a freshly built image on a i2.xlarge node. Short version, the boot fails because the module no longer takes module parameters (modinfo backs this up on ixgbevf-3.3.2).

I'm using a manual `ethtool -C eth0 rx-usecs 1` as a work around for now. 

Given the undocumented removal of a parameter in ixgbevf, who knows what is right or expected...

**Comment by bashtoni** [comment]
This is resolved by 25ae357
