### ISSUE TITLE
aws c5 family compatability

### ISSUE THREAD

**Issue by hhsnow** [BashtonLtd/centos7-ami#6]
To enable initramfs portability to the new generation of instances, the yum package 'dracut-config-generic' can be installed, followed by a 'dracut -f' to regenerate the initramfs objects. 

dracut-config-generic contains:
| $ cat /usr/lib/dracut/dracut.conf.d/02-generic-image.conf
| hostonly="no"

**Comment by bashtoni** [comment]
Thanks!
